/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MapRouteImport } from './routes/map'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as Fy26RouteImport } from './routes/fy26'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const Fy26Route = Fy26RouteImport.update({
  id: '/fy26',
  path: '/fy26',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/fy26': typeof Fy26Route
  '/grants': typeof GrantsRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/fy26': typeof Fy26Route
  '/grants': typeof GrantsRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/fy26': typeof Fy26Route
  '/grants': typeof GrantsRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/fy26' | '/grants' | '/map' | '/methodology'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/fy26' | '/grants' | '/map' | '/methodology'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/fy26'
    | '/grants'
    | '/map'
    | '/methodology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  Fy26Route: typeof Fy26Route
  GrantsRoute: typeof GrantsRoute
  MapRoute: typeof MapRoute
  MethodologyRoute: typeof MethodologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fy26': {
      id: '/fy26'
      path: '/fy26'
      fullPath: '/fy26'
      preLoaderRoute: typeof Fy26RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  Fy26Route: Fy26Route,
  GrantsRoute: GrantsRoute,
  MapRoute: MapRoute,
  MethodologyRoute: MethodologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
