/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakeActionRouteImport } from './routes/take-action'
import { Route as ScorecardRouteImport } from './routes/scorecard'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as IdcRouteImport } from './routes/idc'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as Fy27RouteImport } from './routes/fy27'
import { Route as Fy26RouteImport } from './routes/fy26'
import { Route as ExportPreviewRouteImport } from './routes/export-preview'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BaselineRouteImport } from './routes/baseline'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as InsightsSlugRouteImport } from './routes/insights/$slug'

const TakeActionRoute = TakeActionRouteImport.update({
  id: '/take-action',
  path: '/take-action',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardRoute = ScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const IdcRoute = IdcRouteImport.update({
  id: '/idc',
  path: '/idc',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const Fy27Route = Fy27RouteImport.update({
  id: '/fy27',
  path: '/fy27',
  getParentRoute: () => rootRouteImport,
} as any)
const Fy26Route = Fy26RouteImport.update({
  id: '/fy26',
  path: '/fy26',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportPreviewRoute = ExportPreviewRouteImport.update({
  id: '/export-preview',
  path: '/export-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineRoute = BaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baseline': typeof BaselineRoute
  '/contact': typeof ContactRoute
  '/export-preview': typeof ExportPreviewRoute
  '/fy26': typeof Fy26Route
  '/fy27': typeof Fy27Route
  '/grants': typeof GrantsRoute
  '/idc': typeof IdcRoute
  '/maps': typeof MapsRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/scorecard': typeof ScorecardRoute
  '/take-action': typeof TakeActionRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baseline': typeof BaselineRoute
  '/contact': typeof ContactRoute
  '/export-preview': typeof ExportPreviewRoute
  '/fy26': typeof Fy26Route
  '/fy27': typeof Fy27Route
  '/grants': typeof GrantsRoute
  '/idc': typeof IdcRoute
  '/maps': typeof MapsRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/scorecard': typeof ScorecardRoute
  '/take-action': typeof TakeActionRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights': typeof InsightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baseline': typeof BaselineRoute
  '/contact': typeof ContactRoute
  '/export-preview': typeof ExportPreviewRoute
  '/fy26': typeof Fy26Route
  '/fy27': typeof Fy27Route
  '/grants': typeof GrantsRoute
  '/idc': typeof IdcRoute
  '/maps': typeof MapsRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/scorecard': typeof ScorecardRoute
  '/take-action': typeof TakeActionRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/baseline'
    | '/contact'
    | '/export-preview'
    | '/fy26'
    | '/fy27'
    | '/grants'
    | '/idc'
    | '/maps'
    | '/methodology'
    | '/news'
    | '/scorecard'
    | '/take-action'
    | '/insights/$slug'
    | '/insights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/baseline'
    | '/contact'
    | '/export-preview'
    | '/fy26'
    | '/fy27'
    | '/grants'
    | '/idc'
    | '/maps'
    | '/methodology'
    | '/news'
    | '/scorecard'
    | '/take-action'
    | '/insights/$slug'
    | '/insights'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/baseline'
    | '/contact'
    | '/export-preview'
    | '/fy26'
    | '/fy27'
    | '/grants'
    | '/idc'
    | '/maps'
    | '/methodology'
    | '/news'
    | '/scorecard'
    | '/take-action'
    | '/insights/$slug'
    | '/insights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BaselineRoute: typeof BaselineRoute
  ContactRoute: typeof ContactRoute
  ExportPreviewRoute: typeof ExportPreviewRoute
  Fy26Route: typeof Fy26Route
  Fy27Route: typeof Fy27Route
  GrantsRoute: typeof GrantsRoute
  IdcRoute: typeof IdcRoute
  MapsRoute: typeof MapsRoute
  MethodologyRoute: typeof MethodologyRoute
  NewsRoute: typeof NewsRoute
  ScorecardRoute: typeof ScorecardRoute
  TakeActionRoute: typeof TakeActionRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/take-action': {
      id: '/take-action'
      path: '/take-action'
      fullPath: '/take-action'
      preLoaderRoute: typeof TakeActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard': {
      id: '/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idc': {
      id: '/idc'
      path: '/idc'
      fullPath: '/idc'
      preLoaderRoute: typeof IdcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fy27': {
      id: '/fy27'
      path: '/fy27'
      fullPath: '/fy27'
      preLoaderRoute: typeof Fy27RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fy26': {
      id: '/fy26'
      path: '/fy26'
      fullPath: '/fy26'
      preLoaderRoute: typeof Fy26RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-preview': {
      id: '/export-preview'
      path: '/export-preview'
      fullPath: '/export-preview'
      preLoaderRoute: typeof ExportPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline': {
      id: '/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof BaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BaselineRoute: BaselineRoute,
  ContactRoute: ContactRoute,
  ExportPreviewRoute: ExportPreviewRoute,
  Fy26Route: Fy26Route,
  Fy27Route: Fy27Route,
  GrantsRoute: GrantsRoute,
  IdcRoute: IdcRoute,
  MapsRoute: MapsRoute,
  MethodologyRoute: MethodologyRoute,
  NewsRoute: NewsRoute,
  ScorecardRoute: ScorecardRoute,
  TakeActionRoute: TakeActionRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
