name: Update Data
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: scimap
          environment-file: python/conda_env.yml
          auto-activate-base: false

      - name: Run data update script
        shell: bash -l {0}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          python python/data-update-script.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/data/*.json
          git diff --staged --quiet || git commit -m "Update data files $(date +'%Y-%m-%d')"
          git push
